package i2p.bote.status;

public enum ChangePasswordStatus {
    CHECKING_PASSWORD,
    RE_ENCRYPTING_IDENTITIES,
    RE_ENCRYPTING_ADDRESS_BOOK,
    RE_ENCRYPTING_FOLDER,
    UPDATING_PASSWORD_FILE,
}
